### ISSUE TITLE
PBCH SCS may not  be always 15KHz on live network

### ISSUE THREAD

**Issue by gmg2719** [free5G/free5GRAN#10]
**Describe the bug**

**To Reproduce**
* Error happen during build or installation
* Error happen during execution (If so, please provide the configuration file)
In you code, I found you hard code PBCH SCS to 15KHz. I think this may cause some problem when detect some NR cell with PBCH SCS =30 kHz. May be we should use blind detection of PBCH SCS during cell search procedure. 

**Screenshots**
Add screenshots to help explain your problem.

**System:**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 20.04]
 - Libuhd version

**Additional context**

**Comment by adejavel** [comment]
Hello, could you please mention where did you find this and for which band ?
Thanks.

**Comment by gmg2719** [comment]
Hi, almost all FDD NR bands , for example N1, and some TDD NR bands, for example TDD N41 get PBCH SCS 15kHz. You can refer to 3GPP specs or follow the following table :

![image](https://user-images.githubusercontent.com/26304092/111558719-48d51600-87ca-11eb-93b4-811c9319f5f6.png)

**Comment by adejavel** [comment]
Yes sure, it is already implemented in the code. My question was where in the code did you find that the SCS is fixed ?
For information, in the current release, we do not implement SS Block patterns. The current statement is that Bands below 3Ghz have a SSB SCS of 15khz and bands above have a SSB SCS of 30khz.

**Comment by gmg2719** [comment]
Hi, I just look through part of you code, so I think I was wrong.   "The current statement is that Bands below 3Ghz have a SSB SCS of 15khz and bands above have a SSB SCS of 30khz" is the key to unlock my puzzle. I think this may be true at most of the situation. But not always true, my real intention is that bind the SSB SCS property to specific bands may be a future improvement of your code. For these bands with multiple SSB SCS, we should blind detect all of possible situation.
For example,
n5, n41,n66,n90 is below 3GHz, but they can be with SCS =30kHz

![image](https://user-images.githubusercontent.com/26304092/111720368-adf73d00-8898-11eb-8b87-d0a57ed610c4.png)

![image](https://user-images.githubusercontent.com/26304092/111720514-fb73aa00-8898-11eb-82e7-abde4f257b2e.png)

In fact , in my country, SSB SCS of n41 is 30kHz in live network

**Comment by adejavel** [comment]
Hello,
Thanks for the feedback! Indeed, the current version do not take into account account that a specific band can have multiple SS Block patterns. It will be part of a future release. For information, the current version distinguishes the SS Block pattern and SSB SCS based on frequency.
If required, you can force SSB SCS by setting `band_info` variable [here](https://github.com/free5G/free5GRAN/blob/064621e6ac390d81c59b2f8583873bb6b92434b8/src/main.cc#L345) to either `free5GRAN::BANDWIDTH_15_KHZ` for 15khz SCS or `free5GRAN::BANDWIDTH_30_KHZ` for 30khz SCS.

**Comment by gmg2719** [comment]
Thanks, I get it!
