### ISSUE TITLE
Handover in free5GRAN

### ISSUE THREAD

**Issue by JingqiHuang** [free5G/free5GRAN#11]
Hi,

Thanks for developing free5GRAN! I understand the functions that free5GRAN supports are cell search and band scanning. I would like to know if there is any way to do handover the latest free5GRAN. 

Thanks a lot in advance!

**Comment by adejavel** [comment]
Hello,
Thanks for your message. free5GRAN doesn't support handover yet. We are currently developing the PHY layer of the stack.
Regards.

**Comment by JingqiHuang** [comment]
Thanks for your reply!
