### ISSUE TITLE
Some files are missed

### ISSUE THREAD

**Issue by brightcheng** [free5G/free5GRAN#12]
Hi 
 Some files are missed by "cmake .."
        lib/rf/rf.cpp
        lib/phy/bwp/bwp.cpp
        lib/phy/bwp/bwp.h

**Comment by adejavel** [comment]
Hello, 
Could you please provide some more logs and how to reproduce information ?
Everything is working well with `cmake` on our side.

**Comment by adejavel** [comment]
Hello,
Thanks for the information.
We have committed the missing files.
Regards.
