### ISSUE TITLE
Build fail, sorry, unimplemented: non-trivial designated initializers not supported

### ISSUE THREAD

**Issue by gmg2719** [free5G/free5GRAN#13]
**Describe the bug**
Build failure
**To Reproduce**
Just try to use make command, the following failure occurs:

Scanning dependencies of target free5GRAN
[ 99%] Building CXX object CMakeFiles/free5GRAN.dir/src/main.cc.o
[100%] Building CXX object CMakeFiles/free5GRAN.dir/src/phy/phy.cpp.o
/home/nano/free5GRAN-master-B210/src/phy/phy.cpp: In member function ‘int phy::init(free5GRAN::synchronization_object&, std::condition_variable&)’:
/home/nano/free5GRAN-master-B210/src/phy/phy.cpp:373:49: sorry, unimplemented: non-trivial designated initializers not supported
                               .shiftIndex = pci}};
                                                 ^
/home/nano/free5GRAN-master-B210/src/phy/phy.cpp:373:49: sorry, unimplemented: non-trivial designated initializers not supported
/home/nano/free5GRAN-master-B210/src/phy/phy.cpp:373:49: sorry, unimplemented: non-trivial designated initializers not supported
/home/nano/free5GRAN-master-B210/src/phy/phy.cpp:373:49: sorry, unimplemented: non-trivial designated initializers not supported
/home/nano/free5GRAN-master-B210/src/phy/phy.cpp:373:49: sorry, unimplemented: non-trivial designated initializers not supported
CMakeFiles/free5GRAN.dir/build.make:86: recipe for target 'CMakeFiles/free5GRAN.dir/src/phy/phy.cpp.o' failed
make[2]: *** [CMakeFiles/free5GRAN.dir/src/phy/phy.cpp.o] Error 1
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/free5GRAN.dir/all' failed
make[1]: *** [CMakeFiles/free5GRAN.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Screenshots**

**System:**
 - OS: [Ubuntu]
 - Version [18.03]
 - Libuhd version

**Additional context**

**Comment by adejavel** [comment]
Hello, which version of gcc are you using ?

**Comment by gmg2719** [comment]
gcc verison is :

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.

**Comment by gmg2719** [comment]
I try to upgrade my gcc to 
gcc (Ubuntu 9.3.0-11ubuntu0~18.04.1) 9.3.0
, but the error still remains.  what gcc version need ?  In fact , I compiled pass in all your formal code before last month. I don't know why I can't compile this version of your code.

**Comment by adejavel** [comment]
We will investigate. We do not have the issue here. Thanks for reporting

**Comment by gmg2719** [comment]
I finnally solve it.  After I upgrade my gcc to gcc-9. When I type gcc -v , it returns version 9.3.0. But when I type g++ -v, it returns still version 7.5.0. I think this is the problem, so I try to let ubuntu point to g++-9 when type g++. After this effort, build free5GRAN is OK now.

**Comment by adejavel** [comment]
Thanks for your reply. We will investigate which gcc/g++ version is best for compiling
