### ISSUE TITLE
feature request: SSB-RSRP,RSRQ,SINR measurement result

### ISSUE THREAD

**Issue by gmg2719** [free5G/free5GRAN#5]
**Is your feature request related to a problem? Please describe.**
No, just a new feature request
**Describe the solution you'd like**
may use DMRS or PSS, SSS REs energy to estimate ,  the three measurement value can help me to evaluate the cell quality.

**Describe alternatives you've considered**
No
**Additional context**
No

**Comment by adejavel** [comment]
Hello @gmg2719 ,
From what I understand, measuring RSRQ requires decoding SIB2, SIB3 and SIB4. Is that right ? In that case, RSRQ cannot be computed today as the current version only decodes SIB1.
For RSRP and SINR, it will be released soon

**Comment by gmg2719** [comment]
There are two types of  RSRQs. which are CSI-RSRQ and SSB-RSRQ.  in fact SSB-RSRQ is simple to get. I don't think you must decoding SIBs to get SSB-RSRQ. SSB-RSRQ can be calculated just before cell selection procedure.  in fact you can just use PBCH SS block to estimate SSB-RSRQ by the following equation:
RSRQ= N*RSRP/RSSI ,  N is the RB mumber of PBCH SS block, which is 20. 

CSI-RSRQ is very hard to get, because you must decode lots of RRC message to get CSI-RS configurations.

**Comment by gmg2719** [comment]
By the way, the RSSI in the equation is restricted to PBCH SS block only (that is we only calculate RSSI of the 20 RBs).

**Comment by adejavel** [comment]
Thanks for the answer.
Is that right that those computations are performed before channel equalization ?

**Comment by adejavel** [comment]
This has been added to the last [commit](https://github.com/free5G/free5GRAN/tree/a01b634c6217d6ed41afe372d8604ca37762dfcc). Thanks for your feedback.
