### ISSUE TITLE
suggest add GSCN step variable for each band

### ISSUE THREAD

**Issue by gmg2719** [free5G/free5GRAN#6]
**Is your feature request related to a problem? Please describe.**
A clear description of what the problem is.
GSCN step in most nr bands are 1, but still some bands , such as n41 the step is 3,  n79 the step is 16.  add step variable to control the search procedure in these bands , the search performance can be greatly improved.
**Describe the solution you'd like**
A clear description of what you want to happen.
Add GSCN step variable for each band.
**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.

**Additional context**

**Comment by adejavel** [comment]
Hello, 
Thanks for this suggestion, we will take it into account for the future release.
Regards

**Comment by gmg2719** [comment]
Thanks !
